server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehiclesystem?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 21042004
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1
  google:
    maps:
      api-key: AIzaSyAi-YQpY3WRpflj2QPt7NK3lMnn69Ok9q8

jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=

logging.level.org.springframework.security: DEBUG
